
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftSTARSLASHPCTADD ASSIGN BLOCK DICT EXPORT FLOAT GE GT ID INT LE LIST LONG LPAREN LT MINE MINUS NE NUM PCT PLUS PRINT RPAREN RUN SEPARATOR SLASH STAR STR TUPLE TYPEASSIGN VIEWexpression : term\n                  | expression PLUS term\n                  | expression MINUS termterm : factor\n            | term STAR factor\n            | term SLASH factor\n            | term PCT factorfactor : ID\n              | NUM\n              | LPAREN expression RPAREN\n              | factor LPAREN argsopt RPARENtype : STR\n            | INT\n            | LONG\n            | FLOAT\n            | LIST\n            | TUPLE\n            | DICTattribute : ID TYPEASSIGN typeattributes : attribute\n                  | attributes SEPARATOR attributenew_att : ID TYPEASSIGN STR\n               | ID TYPEASSIGN NUMtest : expression NE expression\n            | expression LT expression\n            | expression LE expression\n            | expression GE expression\n            | expression GT expressionblock : BLOCK ID ASSIGN LPAREN attributes RPAREN\n             | ADD ID ASSIGN LPAREN attributes RPAREN\n             | PRINT ID\n             | RUN ID\n             | MINE ID\n             | EXPORT ID\n             | VIEW IDargsopt : args\n               | emptyargs : expression SEPARATOR args\n            | expressionempty :'
    
_lr_action_items = {'ID':([0,6,7,8,9,10,11,12,25,],[4,4,4,4,4,4,4,4,4,]),'NUM':([0,6,7,8,9,10,11,12,25,],[5,5,5,5,5,5,5,5,5,]),'LPAREN':([0,3,4,5,6,7,8,9,10,11,12,16,17,18,23,24,25,],[6,12,-8,-9,6,6,6,6,6,6,6,12,12,12,-10,-11,6,]),'$end':([1,2,3,4,5,14,15,16,17,18,23,24,],[0,-1,-4,-8,-9,-2,-3,-5,-6,-7,-10,-11,]),'PLUS':([1,2,3,4,5,13,14,15,16,17,18,22,23,24,],[7,-1,-4,-8,-9,7,-2,-3,-5,-6,-7,7,-10,-11,]),'MINUS':([1,2,3,4,5,13,14,15,16,17,18,22,23,24,],[8,-1,-4,-8,-9,8,-2,-3,-5,-6,-7,8,-10,-11,]),'RPAREN':([2,3,4,5,12,13,14,15,16,17,18,19,20,21,22,23,24,26,],[-1,-4,-8,-9,-40,23,-2,-3,-5,-6,-7,24,-36,-37,-39,-10,-11,-38,]),'SEPARATOR':([2,3,4,5,14,15,16,17,18,22,23,24,],[-1,-4,-8,-9,-2,-3,-5,-6,-7,25,-10,-11,]),'STAR':([2,3,4,5,14,15,16,17,18,23,24,],[9,-4,-8,-9,9,9,-5,-6,-7,-10,-11,]),'SLASH':([2,3,4,5,14,15,16,17,18,23,24,],[10,-4,-8,-9,10,10,-5,-6,-7,-10,-11,]),'PCT':([2,3,4,5,14,15,16,17,18,23,24,],[11,-4,-8,-9,11,11,-5,-6,-7,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,12,25,],[1,13,22,22,]),'term':([0,6,7,8,12,25,],[2,2,14,15,2,2,]),'factor':([0,6,7,8,9,10,11,12,25,],[3,3,3,3,16,17,18,3,3,]),'argsopt':([12,],[19,]),'args':([12,25,],[20,26,]),'empty':([12,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term','expression',1,'p_expr','Final_PL_HW.py',141),
  ('expression -> expression PLUS term','expression',3,'p_expr','Final_PL_HW.py',142),
  ('expression -> expression MINUS term','expression',3,'p_expr','Final_PL_HW.py',143),
  ('term -> factor','term',1,'p_term','Final_PL_HW.py',165),
  ('term -> term STAR factor','term',3,'p_term','Final_PL_HW.py',166),
  ('term -> term SLASH factor','term',3,'p_term','Final_PL_HW.py',167),
  ('term -> term PCT factor','term',3,'p_term','Final_PL_HW.py',168),
  ('factor -> ID','factor',1,'p_factor','Final_PL_HW.py',191),
  ('factor -> NUM','factor',1,'p_factor','Final_PL_HW.py',192),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','Final_PL_HW.py',193),
  ('factor -> factor LPAREN argsopt RPAREN','factor',4,'p_factor','Final_PL_HW.py',194),
  ('type -> STR','type',1,'p_type','Final_PL_HW.py',207),
  ('type -> INT','type',1,'p_type','Final_PL_HW.py',208),
  ('type -> LONG','type',1,'p_type','Final_PL_HW.py',209),
  ('type -> FLOAT','type',1,'p_type','Final_PL_HW.py',210),
  ('type -> LIST','type',1,'p_type','Final_PL_HW.py',211),
  ('type -> TUPLE','type',1,'p_type','Final_PL_HW.py',212),
  ('type -> DICT','type',1,'p_type','Final_PL_HW.py',213),
  ('attribute -> ID TYPEASSIGN type','attribute',3,'p_attribute','Final_PL_HW.py',220),
  ('attributes -> attribute','attributes',1,'p_attributes','Final_PL_HW.py',224),
  ('attributes -> attributes SEPARATOR attribute','attributes',3,'p_attributes','Final_PL_HW.py',225),
  ('new_att -> ID TYPEASSIGN STR','new_att',3,'p_new_att','Final_PL_HW.py',235),
  ('new_att -> ID TYPEASSIGN NUM','new_att',3,'p_new_att','Final_PL_HW.py',236),
  ('test -> expression NE expression','test',3,'p_test','Final_PL_HW.py',254),
  ('test -> expression LT expression','test',3,'p_test','Final_PL_HW.py',255),
  ('test -> expression LE expression','test',3,'p_test','Final_PL_HW.py',256),
  ('test -> expression GE expression','test',3,'p_test','Final_PL_HW.py',257),
  ('test -> expression GT expression','test',3,'p_test','Final_PL_HW.py',258),
  ('block -> BLOCK ID ASSIGN LPAREN attributes RPAREN','block',6,'p_block','Final_PL_HW.py',282),
  ('block -> ADD ID ASSIGN LPAREN attributes RPAREN','block',6,'p_block','Final_PL_HW.py',283),
  ('block -> PRINT ID','block',2,'p_block','Final_PL_HW.py',284),
  ('block -> RUN ID','block',2,'p_block','Final_PL_HW.py',285),
  ('block -> MINE ID','block',2,'p_block','Final_PL_HW.py',286),
  ('block -> EXPORT ID','block',2,'p_block','Final_PL_HW.py',287),
  ('block -> VIEW ID','block',2,'p_block','Final_PL_HW.py',288),
  ('argsopt -> args','argsopt',1,'p_argsopt','Final_PL_HW.py',315),
  ('argsopt -> empty','argsopt',1,'p_argsopt','Final_PL_HW.py',316),
  ('args -> expression SEPARATOR args','args',3,'p_args','Final_PL_HW.py',320),
  ('args -> expression','args',1,'p_args','Final_PL_HW.py',321),
  ('empty -> <empty>','empty',0,'p_empty','Final_PL_HW.py',325),
]
